### ISSUE TITLE
Trouble installing -- 2-3 hour downloads?

### ISSUE THREAD

**Issue by ckcollab** [KumaTea/tensorflow-aarch64#2]
Hey there, thank you so much for this! We just got a new M1 macbook but are stuck working on a current project because of `tensorflow-cpu` not being available with an arm wheel.

It appears like these new wheels should be the perfect solution for us, but unfortunately the download times are pretty extreme and end up causing timeouts. Is this something we can maybe help with? I just got a 1 gig symmetrical fiber connection at my house, I wouldn't mind mirroring things or something for a while to help out folks!

**Comment by KumaTea** [comment]
Hi, I believe that there might be something wrong in AWS S3, which hosts Linaro's files. 

GitHub releases are also hosted on S3 but it seems normal.

Maybe we can only wait it to be fixed...

![image](https://user-images.githubusercontent.com/36222458/127973721-dff09e73-7baf-4c22-9945-b5199760057b.png)

**Comment by ckcollab** [comment]
So strange, hopefully things just resolve on their own... thanks for the quick response
